modid = "hexdoc"
default_lang = "en_us"
default_branch = "main"

_export_root = "src/hexdoc/_export"
resource_dirs = [  # top takes priority
    { path="{^_export_root}/resources", reexport=false },
]
export_dir = "{_export_root}/generated"
